import {
  BACKEND_URL,
  APPWRITE_PROJECT_ID,
  ADMIN_HOST_ORIGIN,
  NINJAS_API,
  APPWRITE_SARTHAK_DATABASE,
  APPWRITE_COLLECTION_ADMIN_USERS,
  APPWRITE_COLLECTION_CHAPTERS,
  APPWRITE_COLLECTION_CONCEPTS,
  APPWRITE_COLLECTION_MOCKTEST,
  APPWRITE_COLLECTION_MOCK_TEST_DRIVER,
  APPWRITE_COLLECTION_QUESTIONS,
  APPWRITE_COLLECTION_STANDARDS,
  APPWRITE_COLLECTION_SUBJECTS,
  APPWRITE_COLLECTION_PRODUCTS,
  APPWRITE_COLLECTION_STUDENTS,
  APPWRITE_BUCKET_QUESTION_FILES,
  APPWRITE_BUCKET_PRODUCT_FILES,
} from "@env";

export const APPWRITE_API = {
  backendUrl: BACKEND_URL,
  projectId: APPWRITE_PROJECT_ID,
  databaseId: APPWRITE_SARTHAK_DATABASE,
  adminHostOrigin: ADMIN_HOST_ORIGIN,
  collections: {
    adminUsers: APPWRITE_COLLECTION_ADMIN_USERS,
    chapters: APPWRITE_COLLECTION_CHAPTERS,
    concepts: APPWRITE_COLLECTION_CONCEPTS,
    mockTest: APPWRITE_COLLECTION_MOCKTEST,
    mockTestDriver: APPWRITE_COLLECTION_MOCK_TEST_DRIVER,
    questions: APPWRITE_COLLECTION_QUESTIONS,
    standards: APPWRITE_COLLECTION_STANDARDS,
    subjects: APPWRITE_COLLECTION_SUBJECTS,
    products: APPWRITE_COLLECTION_PRODUCTS,
    students: APPWRITE_COLLECTION_STUDENTS,
  },
  buckets: {
    questionFiles: APPWRITE_BUCKET_QUESTION_FILES,
    productFiles: APPWRITE_BUCKET_PRODUCT_FILES,
  },
};

export const NINJA_API = {
  key: NINJAS_API,
};
